# 넘파이 연산

In [2]:
import numpy as np # 넘파이 라이브러리 로드

## 1. 넘파이 기본 연산

### 1.1 넘파이 사칙 연산

In [12]:
# 벡터
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.full_like(v1, 5)

print("v1 + v2 = ", v1 + v2) # v1 + v2 =  [ 6  7  8  9 10]
print("v1 - v2 = ", v1 - v2) # v1 - v2 =  [-4 -3 -2 -1  0]
print("v1 * v2 = ", v1 * v2) # v1 * v2 =  [ 5 10 15 20 25]
print("v1 / v2 = ", v1 / v2) # v1 / v2 =  [0.2 0.4 0.6 0.8 1. ]

v1 + v2 =  [ 6  7  8  9 10]
v1 - v2 =  [-4 -3 -2 -1  0]
v1 * v2 =  [ 5 10 15 20 25]
v1 / v2 =  [0.2 0.4 0.6 0.8 1. ]


In [13]:
# 행렬
m1 = np.arange(1, 10).reshape(3, 3)
m2 = np.full_like(m1, 5)

print("m1 + m2 = ", m1 + m2) 
# m1 + m2 =  [[ 6  7  8]
#  [ 9 10 11]
#  [12 13 14]]
print("m1 - m2 = ", m1 - m2)
# m1 - m2 =  [[-4 -3 -2]
#  [-1  0  1]
#  [ 2  3  4]]
print("m1 * m2 = ", m1 * m2) 
# m1 * m2 =  [[ 5 10 15]
#  [20 25 30]
#  [35 40 45]]
print("m1 / m2 = ", m1 / m2)
# m1 / m2 =  [[0.2 0.4 0.6]
#  [0.8 1.  1.2]
#  [1.4 1.6 1.8]]

m1 + m2 =  [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
m1 - m2 =  [[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]
m1 * m2 =  [[ 5 10 15]
 [20 25 30]
 [35 40 45]]
m1 / m2 =  [[0.2 0.4 0.6]
 [0.8 1.  1.2]
 [1.4 1.6 1.8]]


In [15]:
# 오류가 발생하는 코드
v1 = np.arange(1, 10)
v2 = np.arange(1, 9)

print("v1 + v2 = ", v1 + v2)

ValueError: operands could not be broadcast together with shapes (9,) (8,) 

In [20]:
# 벡터
v1 = np.arange(1, 5)
v2 = np.arange(5, 1, -1)

print("v1 ** v2 = ", v1 ** v2) # v1 ** v2 =  [ 1 16 27 16]
print("v1 // v2 = ", v1 // v2) # v1 // v2 =  [0 0 1 2]
print("v1 % v2 = ", v1 % v2) # v1 % v2 =  [1 2 0 0]

v1 ** v2 =  [ 1 16 27 16]
v1 // v2 =  [0 0 1 2]
v1 % v2 =  [1 2 0 0]


In [21]:
# 행렬
m1 = np.arange(1, 10).reshape(3, 3)
m2 = np.arange(10, 1, -1).reshape(3, 3)

print("m1 ** m2 = ", m1 ** m2) 
# m1 ** m2 =  [[    1   512  6561]
#  [16384 15625  7776]
#  [ 2401   512    81]]
print("m1 // m2 = ", m1 // m2) 
# m1 // m2 =  [[0 0 0]
#  [0 0 1]
#  [1 2 4]]
print("m1 % m2 = ", m1 % m2) 
# m1 % m2 =  [[1 2 3]
#  [4 5 1]
#  [3 2 1]]

m1 ** m2 =  [[    1   512  6561]
 [16384 15625  7776]
 [ 2401   512    81]]
m1 // m2 =  [[0 0 0]
 [0 0 1]
 [1 2 4]]
m1 % m2 =  [[1 2 3]
 [4 5 1]
 [3 2 1]]


In [9]:
# 벡터
sin_v = np.sin(np.arange(1, 6))
cos_v = np.cos(np.arange(1, 6))
tan_v = np.tan(np.arange(1, 6))
arcsin_v = np.arcsin(np.linspace(0, 1, 5))
arccos_v = np.arccos(np.linspace(0, 1, 5))
arctan_v = np.arctan(np.linspace(0, 1, 5))

print("sin_v = \n", sin_v) # [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
print("cos_v = \n", cos_v) # [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
print("tan_v = \n", tan_v) # [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]
print("arcsin_v = \n", arcsin_v) # [0.         0.25268026 0.52359878 0.84806208 1.57079633]
print("arccos_v = \n", arccos_v) # [1.57079633 1.31811607 1.04719755 0.72273425 0.        ]
print("arctan_v = \n", arctan_v) # [0.         0.24497866 0.46364761 0.64350111 0.78539816]

sin_v = 
 [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
cos_v = 
 [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
tan_v = 
 [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]
arcsin_v = 
 [0.         0.25268026 0.52359878 0.84806208 1.57079633]
arccos_v = 
 [1.57079633 1.31811607 1.04719755 0.72273425 0.        ]
arctan_v = 
 [0.         0.24497866 0.46364761 0.64350111 0.78539816]


In [10]:
r1 = np.ceil(np.random.rand(2, 5))
r2 = np.floor(np.random.rand(2, 5))
r3_int = np.round(np.random.rand(2, 5))
r3_1 = np.round(np.random.rand(2, 5), 1)
r3_2 = np.round(np.random.rand(2, 5), 2)
r4 = np.around(np.random.rand(2, 5))

print("r1 = \n", r1)
#  [[1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]]
print("r2 = \n", r2)
#  [[0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0.]]
print("r3_int = \n", r3_int)
#  [[1. 0. 1. 0. 0.]
#  [0. 1. 0. 1. 1.]]
print("r3_1 = \n", r3_1)
#  [[0.3 1.  0.2 0.6 0.4]
#  [0.5 0.  0.6 0.5 0.1]]
print("r3_2 = \n", r3_2)
#  [[0.44 0.08 0.14 0.87 0.07]
#  [0.95 0.85 0.87 0.23 0.19]]
print("r4 = \n", r4)
#  [[1. 0. 0. 1. 0.]
#  [0. 1. 0. 1. 0.]]

r1 = 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
r2 = 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
r3_int = 
 [[1. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0.]]
r3_1 = 
 [[0.6 0.2 0.1 0.9 1. ]
 [0.8 0.3 0.1 0.7 0.4]]
r3_2 = 
 [[0.12 0.5  0.03 0.91 0.26]
 [0.66 0.31 0.52 0.55 0.18]]
r4 = 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0.]]


In [11]:
np.random.seed(42)

e1 = np.exp(np.arange(1, 6)) # np.exp([a, b, c]) = [exp(a), exp(b), exp(c)]
e2 = np.exp2(np.arange(1, 6)) # np.exp2([a, b, c]) = [2^(a), 2^(b), 2^(c)]
e3 = np.expm1(np.arange(1, 6)) # np.expm1([a, b, c]) = [e^(a)-1, e^(b)-1, e^(c)-1]

print(e1) # [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
print(e2) # [ 2.  4.  8. 16. 32.]
print(e3) # 

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 2.  4.  8. 16. 32.]
[  1.71828183   6.3890561   19.08553692  53.59815003 147.4131591 ]


In [12]:
np.random.seed(42)

l1 = np.log(np.arange(1, 6)) # np.log([a, b, c]) = [ln(a), ln(b), ln(c)]
l2 = np.log10(np.arange(1, 6)) # np.log10([a, b, c]) = [log_10(a), log_10(b), log_10(c)]
l3 = np.log2(np.arange(1, 6)) # np.log2([a, b, c]) = [log_2(a), log_2(b), log_2(c)]
l4 = np.log1p(np.arange(1, 6)) # np.expm1([a, b, c]) = [ln(a+1), ln(b+1), ln(c+1)]

print(l1) # [0.         0.69314718 1.09861229 1.38629436 1.60943791]
print(l2) # [0.         0.30103    0.47712125 0.60205999 0.69897   ]
print(l3) # [0.         1.         1.5849625  2.         2.32192809]
print(l4) # [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [2]:
np.random.seed(42)

s1 = np.sqrt(np.arange(1, 6)) # np.log([a, b, c]) = [ln(a), ln(b), ln(c)]
s2 = np.square(np.arange(1, 6)) # np.log10([a, b, c]) = [log_10(a), log_10(b), log_10(c)]

print(s1) # [1.         1.41421356 1.73205081 2.         2.23606798]
print(s2) # [ 1  4  9 16 25]

[1.         1.41421356 1.73205081 2.         2.23606798]
[ 1  4  9 16 25]
