In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3, 4])

print(a + b)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [3]:
a1 = np.array([1, 2, 3])
b1 = np.array([1])

print(a1 + b1) # [2 3 4]

[2 3 4]


In [4]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
b2 = np.array([1, 1, 1])

print(a2 + b2)
# [[2 3 4]
#  [5 6 7]]

[[2 3 4]
 [5 6 7]]


In [5]:
print("{} + {} = {}".format(a1.shape, b1.shape, (a1+b1).shape)) # (3,) + (1,) = (3,)
print("{} + {} = {}".format(a2.shape, b2.shape, (a2+b2).shape)) # (2, 3) + (3,) = (2, 3)

(3,) + (1,) = (3,)
(2, 3) + (3,) = (2, 3)


In [6]:
a3 = np.array([[1, 2, 3]])
b3 = np.array([[1], [2], [3]])

print(a3 + b3)
# [[2 3 4]
#  [3 4 5]
#  [4 5 6]]
print("{} + {} = {}".format(a3.shape, b3.shape, (a3+b3).shape)) # (1, 3) + (3, 1) = (3, 3)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
(1, 3) + (3, 1) = (3, 3)


In [7]:
a4 = np.arange(1, 28).reshape(3, 3, 3)
b4 = np.arange(1, 10).reshape(3, 3)

print(a4 + b4)
# [[[ 2  4  6]
#   [ 8 10 12]
#   [14 16 18]]

#  [[11 13 15]
#   [17 19 21]
#   [23 25 27]]

#  [[20 22 24]
#   [26 28 30]
#   [32 34 36]]]
print("{} + {} = {}".format(a4.shape, b4.shape, (a4+b4).shape)) # (3, 3, 3) + (3, 3) = (3, 3, 3)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[11 13 15]
  [17 19 21]
  [23 25 27]]

 [[20 22 24]
  [26 28 30]
  [32 34 36]]]
(3, 3, 3) + (3, 3) = (3, 3, 3)


In [9]:
a5 = np.arange(1, 28).reshape(3, 3, 3)
b5 = np.arange(1, 4).reshape(3, 1)

print(a5 + b5)
# [[[ 2  3  4]
#   [ 6  7  8]
#   [10 11 12]]

#  [[11 12 13]
#   [15 16 17]
#   [19 20 21]]

#  [[20 21 22]
#   [24 25 26]
#   [28 29 30]]]
print("{} + {} = {}".format(a5.shape, b5.shape, (a5+b5).shape)) # (3, 3, 3) + (3, 1) = (3, 3, 3)

[[[ 2  3  4]
  [ 6  7  8]
  [10 11 12]]

 [[11 12 13]
  [15 16 17]
  [19 20 21]]

 [[20 21 22]
  [24 25 26]
  [28 29 30]]]
(3, 3, 3) + (3, 1) = (3, 3, 3)


In [12]:
a6 = np.arange(1, 28).reshape(3, 3, 3)
b6 = np.arange(1, 7).reshape(3, 2)

print(a6 + b6)

[[1 2]
 [3 4]
 [5 6]]


ValueError: operands could not be broadcast together with shapes (3,3,3) (3,2) 