In [8]:
import numpy as np

In [11]:
a = np.array([0, 1, 2]) # shape=(3, )

np.tile(a, 2) # shape=(6,)
# array([0, 1, 2, 0, 1, 2])

array([0, 1, 2, 0, 1, 2])

In [17]:
np.tile(a, (1, 2)) # shape=(1, 6)
# array([[0, 1, 2, 0, 1, 2]])

array([[0, 1, 2, 0, 1, 2]])

In [22]:
np.tile(a, (2, 1)) # shape=(2, 3)
# array([[0, 1, 2],
#        [0, 1, 2]])

array([[0, 1, 2],
       [0, 1, 2]])

In [34]:
np.tile(a, (2, 2)) # shape=(2, 6)
# array([[0, 1, 2, 0, 1, 2],
#        [0, 1, 2, 0, 1, 2]])

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [44]:
np.tile(a, (2, 1, 1)) # shape=(2, 1, 3)
# array([[[0, 1, 2]],

#        [[0, 1, 2]]])

array([[[0, 1, 2]],

       [[0, 1, 2]]])

In [45]:
np.tile(a, (1, 2, 1)) # shape=(1, 2, 3)
# array([[[0, 1, 2],
#         [0, 1, 2]]])

array([[[0, 1, 2],
        [0, 1, 2]]])

In [33]:
np.tile(a, (1, 1, 2)) # shape=(1, 1, 6)
# array([[[0, 1, 2, 0, 1, 2]]])

array([[[0, 1, 2, 0, 1, 2]]])

In [48]:
np.tile(a, (2, 2, 1)).shape # shape=(2, 2, 3)
# array([[[0, 1, 2],
#         [0, 1, 2]],

#        [[0, 1, 2],
#         [0, 1, 2]]])

(2, 2, 3)

In [50]:
np.tile(a, (2, 1, 2)) # shape=(2, 1, 6)
# array([[[0, 1, 2, 0, 1, 2]],

#        [[0, 1, 2, 0, 1, 2]]])

array([[[0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2]]])

In [55]:
np.tile(a, (1, 2, 2)) # shape=(1, 2, 6)
# array([[[0, 1, 2, 0, 1, 2],
#         [0, 1, 2, 0, 1, 2]]])

array([[[0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2]]])

In [58]:
np.tile(a, (2, 2, 2)) # shape=(2, 2, 6)
# array([[[0, 1, 2, 0, 1, 2],
#         [0, 1, 2, 0, 1, 2]],

#        [[0, 1, 2, 0, 1, 2],
#         [0, 1, 2, 0, 1, 2]]])

(2, 2, 6)

In [61]:
np.repeat(3, 4) # (4,)
# array([3, 3, 3, 3])

array([3, 3, 3, 3])

In [68]:
a = np.array([0, 1, 2]) # shape=(3, )

np.repeat(a, 2) # shape=(6,)
# array([0, 0, 1, 1, 2, 2])

array([0, 0, 1, 1, 2, 2])

In [81]:
a = np.array([[0, 1, 2], [3, 4, 5]]) # shape=(2, 3)

np.repeat(a, 2) # shape=(12,)
# array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [112]:
a = np.array([[0, 1, 2], [3, 4, 5]]) # shape=(2, 3)

np.repeat(a, 2, axis=0) # shape=(4, 3)
# array([[0, 1, 2],
#        [0, 1, 2],
#        [3, 4, 5],
#        [3, 4, 5]])

array([[0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [3, 4, 5]])

In [107]:
np.repeat(a, (1, 2), axis=0) # shape=(3, 3)
# array([[0, 1, 2],
#        [3, 4, 5],
#        [3, 4, 5]])

array([[0, 1, 2],
       [3, 4, 5],
       [3, 4, 5]])

In [110]:
np.repeat(a, (2, 2), axis=0) # shape=(4, 3)
# array([[0, 1, 2],
#        [0, 1, 2],
#        [3, 4, 5],
#        [3, 4, 5]])

array([[0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [3, 4, 5]])