In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2], [3, 4]]) # a.shape=(2, 2)
b = np.array([[5, 6]]) # b.shape=(2, 1)

In [3]:
np.concatenate((a, b), axis=0)
# array([[1, 2],
#        [3, 4],
#        [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
np.stack((a, b), axis=0)
# array([[1, 2],
#        [3, 4],
#        [5, 6]])

ValueError: all input arrays must have the same shape

In [ ]:
a = np.array([[1, 2], [3, 4]]) # a.shape=(2, 2)
b = np.array([[5, 6], [7, 8]]) # b.shape=(2, 2)

In [ ]:
np.concatenate((a, b), axis=0) # shape=(4, 2)
# array([[1, 2],
#        [3, 4],
#        [5, 6],
#        [7, 8]])

In [ ]:
np.stack((a, b), axis=0) # shape=(2, 2, 2)
# array([[[1, 2],
#         [3, 4]],

#        [[5, 6],
#         [7, 8]]])

In [ ]:
np.stack((a, b), axis=1) # shape=(2, 2, 2)
# array([[[1, 2],
#         [5, 6]],

#        [[3, 4],
#         [7, 8]]])

In [ ]:
np.stack((a, b), axis=2) # shape=(2, 2, 2)
# array([[[1, 5],
#         [2, 6]],

#        [[3, 7],
#         [4, 8]]])

In [ ]:
a_re = a.reshape((1, 2, 2))
b_re = b.reshape((1, 2, 2))

np.concatenate((a_re, b_re), axis=0) # shape=(2, 2, 2)
# array([[[1, 2],
#         [3, 4]],

#        [[5, 6],
#         [7, 8]]])

In [ ]:
a_re = a.reshape((2, 1, 2))
b_re = b.reshape((2, 1, 2))

np.concatenate((a_re, b_re), axis=1) # shape=(2, 2, 2)
# array([[[1, 2],
#         [5, 6]],

#        [[3, 4],
#         [7, 8]]])

In [5]:
for i in range(x.shape[0]) :
    for j in range(x.shape[1]) :
        for k in range(x.shape[2]) :
            print("x[{}, {}, {}]={}".format(i, j, k, x[i, j, k]))
        print("+"*10)
    print("*"*10)

NameError: name 'x' is not defined

In [6]:
a_re = a.reshape((2, 2, 1))
b_re = b.reshape((2, 2, 1))

np.concatenate((a_re, b_re), axis=2) # shape=(2, 2, 2)
# array([[[1, 5],
#         [2, 6]],

#        [[3, 7],
#         [4, 8]]])

ValueError: cannot reshape array of size 2 into shape (2,2,1)

In [7]:
np.concatenate((a, b), axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [8]:
a = np.array((1,2,3))
b = np.array((4,5,6))

np.hstack((a,b)) # shape=(6,)
# array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [9]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])

np.hstack((a,b))# shape=(3, 2)
# array([[1, 2],
#        [2, 3],
#        [3, 4]])

array([[1, 2],
       [2, 3],
       [3, 4]])

In [10]:
a = np.array((1,2,3))
b = np.array((4,5,6))

np.concatenate((a,b), axis=0) # shape=(6,)
# array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [11]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])

np.concatenate((a,b), axis=1)# shape=(3, 2)
# array([[1, 2],
#        [2, 3],
#        [3, 4]])

array([[1, 2],
       [2, 3],
       [3, 4]])

In [42]:
a = np.array([[1, 2], [3, 4]]) # a.shape=(2, 2)
b = np.array([[5, 6], [7, 8]]) # b.shape=(2, 2)

np.hstack((a,b))# shape=(2, 4)
# array([[1, 2, 5, 6],
#        [3, 4, 7, 8]])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [43]:
a = np.array([[1, 2], [3, 4]]) # a.shape=(2, 2)
b = np.array([[5, 6], [7, 8]]) # b.shape=(2, 2)

np.concatenate((a,b), axis=1)# shape=(2, 4)
# array([[1, 2, 5, 6],
#        [3, 4, 7, 8]])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [46]:
a = np.array([[1, 2], [3, 4]]) # a.shape=(2, 2)
b = np.array([[5, 6], [7, 8]]) # b.shape=(2, 2)

np.r_[a, b]# shape=(2, 4)
# array([[1, 2, 5, 6],
#        [3, 4, 7, 8]])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.vstack((a,b))
# array([[1, 2, 3],
#        [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

np.vstack((a,b))
# array([[1],
#        [2],
#        [3],
#        [4],
#        [5],
#        [6]])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [16]:
a = np.array([[1, 2], [3, 4]]) # a.shape=(2, 2)
b = np.array([[5, 6], [7, 8]]) # b.shape=(2, 2)

np.vstack((a,b))# shape=(4, 2)
# array([[1, 2],
#        [3, 4],
#        [5, 6],
#        [7, 8]])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [17]:
np.concatenate((a,b), axis=0)# shape=(4, 2)
# array([[1, 2],
#        [3, 4],
#        [5, 6],
#        [7, 8]])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.dstack((a, b)) # shape=(1, 3, 2)
# array([[[1, 4],
#         [2, 5],
#         [3, 6]]])

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [19]:
np.stack((a, b), axis=-1) # shape=(1, 3, 2)
# array([[1, 4],
#        [2, 5],
#        [3, 6]])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [20]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

np.dstack((a,b)) # shape=(3, 1, 2)
# array([[[1, 4]],

#        [[2, 5]],

#        [[3, 6]]])

array([[[1, 4]],

       [[2, 5]],

       [[3, 6]]])

In [21]:
np.stack((a,b), axis=-1) # shape=(3, 1, 2)
# array([[[1, 4]],

#        [[2, 5]],

#        [[3, 6]]])

array([[[1, 4]],

       [[2, 5]],

       [[3, 6]]])

In [22]:
a = np.array([[1, 2], [3, 4]]) # a.shape=(2, 2)
b = np.array([[5, 6], [7, 8]]) # b.shape=(2, 2)

np.dstack((a,b)).shape# shape=(2, 2, 2)
# array([[[1, 5],
#         [2, 6]],

#        [[3, 7],
#         [4, 8]]])

(2, 2, 2)

In [23]:
np.stack((a,b), axis=-1)# shape=(2, 2, 2)
# array([[[1, 5],
#         [2, 6]],

#        [[3, 7],
#         [4, 8]]])

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [33]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.column_stack((a,b)) # shape=(3, 2)
# array([[1, 4],
#        [2, 5],
#        [3, 6]])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [36]:
a = np.array([[1,2,3],[4, 5, 6]])
b = np.array([[7,8,9], [10, 11, 12]])

np.column_stack((a,b)) # shape=(2, 6)
# array([[ 1,  2,  3,  7,  8,  9],
#        [ 4,  5,  6, 10, 11, 12]])

(2, 6)

In [38]:
np.concatenate((a,b), axis=1) # shape=(2, 6)
# array([[ 1,  2,  3,  7,  8,  9],
#        [ 4,  5,  6, 10, 11, 12]])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])