In [1]:
import numpy as np

In [10]:
v1 = np.array([1, 2, 3]) # = <1, 2, 3>
v2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) # = <1, 2, 3, 4, 5 ,6, 7, 8, 9, 10>

m1 = np.array([[1, 2, 3], [4, 5, 6]]) 
# [[1, 2, 3],
#  [4, 5, 6]]

m2 = np.array([[1, 2, 3, 4, 5], [7, 8, 9, 10, 11]]) 
# [[ 1,  2,  3,  4,  5],
#  [ 7,  8,  9, 10, 11]]

In [13]:
print(v1.dtype) # int64 
print(v2.dtype) # int64
print(m1.dtype) # int64
print(m2.dtype) # int64

int64
int64
int64
int64


In [16]:
v1 = np.array([1, 2, 3], dtype=np.int32) # = <1, 2, 3>
v2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=np.float32) # = <1, 2, 3, 4, 5 ,6, 7, 8, 9, 10>

m1 = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64) 
# [[1, 2, 3],
#  [4, 5, 6]]

m2 = np.array([[1, 2, 3, 4, 5], [7, 8, 9, 10, 11]], dtype=np.int16) 
# [[ 1,  2,  3,  4,  5],
#  [ 7,  8,  9, 10, 11]]

In [24]:
print(v1.dtype) # int32 
print(v2.dtype) # float32
print(m1.dtype) # flaot64
print(m2.dtype) # int16

int32
float32
float64
int16


In [19]:
print(v1.shape) # (3,)
print(v2.shape) # (10,)
print(m1.shape) # (2, 3)
print(m2.shape) # (2, 5)

(3,)
(10,)
(2, 3)
(2, 5)


In [21]:
print(v1.ndim) # 1
print(v2.ndim) # 1
print(m1.ndim) # 2
print(m2.ndim) # 2

1
1
2
2


In [26]:
print(v1.size) # 3
print(v2.size) # 10
print(m1.size) # 6
print(m2.size) # 10

3
10
6
10


In [32]:
z1 = np.zeros((10)) # [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
z2 = np.zeros((10, 20))
# [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
z3 = np.zeros_like(v1) # [0 0 0]
z4 = np.zeros_like(m2)
# [[0 0 0 0 0]
#  [0 0 0 0 0]]

In [33]:
print(z1.shape) # (10,)
print(z2.shape) # (10, 20)
print(z3.shape) # (3,)
print(z4.shape) # (2, 5)

(10,)
(10, 20)
(3,)
(2, 5)


In [38]:
o1 = np.ones((10)) # [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
o2 = np.ones((10, 20))
# [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
o3 = np.ones_like(v1) # [1 1 1]
o4 = np.ones_like(m2)
# [[1 1 1 1 1]
#  [1 1 1 1 1]]

In [39]:
print(o1.shape) # (10,)
print(o2.shape) # (10, 20)
print(o3.shape) # (3,)
print(o4.shape) # (2, 5)

(10,)
(10, 20)
(3,)
(2, 5)


In [50]:
f1 = np.full((10), 10) # [10 10 10 10 10 10 10 10 10 10]
f2 = np.full((10, 20), 50)
# [[50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50]
#  [50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50]
#  [50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50]
#  [50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50]
#  [50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50]
#  [50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50]
#  [50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50]
#  [50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50]
#  [50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50]
#  [50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50]]
f3 = np.full_like(v1, 54) # [54 54 54]
f4 = np.full_like(m2, 12)
# [[12 12 12 12 12]
#  [12 12 12 12 12]]

In [47]:
print(f1.shape) # (10,)
print(f2.shape) # (10, 20)
print(f3.shape) # (3,)
print(f4.shape) # (2, 5)

(10,)
(10, 20)
(3,)
(2, 5)


In [67]:
# np.arange(start(default=0), end, step, dtype)
ar1 = np.arange(10) # [0 1 2 3 4 5 6 7 8 9]
ar2 = np.arange(5, 10) # [5 6 7 8 9]
ar3 = np.arange(1, 10, 2) # [1 3 5 7 9]

In [68]:
arm1 = np.arange(10).reshape(2, 5) 
# [[0 1 2 3 4]
#  [5 6 7 8 9]]
arm2 = np.arange(5, 10).reshape(1, 5) # [[5 6 7 8 9]]
arm3 = np.arange(1, 10, 2).reshape(5, 1) 
# [[1]
#  [3]
#  [5]
#  [7]
#  [9]]

In [73]:
print(arm1.shape) # (2, 5)
print(arm2.shape) # (1, 5)
print(arm3.shape) # (5, 1)

(2, 5)
(1, 5)
(5, 1)


In [85]:
arm4 = np.arange(10).reshape(1, 5)

ValueError: cannot reshape array of size 10 into shape (1,5)

In [82]:
# np.linspace(start, end, size)
li1 = np.linspace(0, 2, 9) # [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
li2 = np.linspace(-10, 20, 10)
# [-10.          -6.66666667  -3.33333333   0.           3.33333333
#    6.66666667  10.          13.33333333  16.66666667  20.        ]
li3 = np.linspace(100, 10000, 20)
# [  100.           621.05263158  1142.10526316  1663.15789474
#   2184.21052632  2705.26315789  3226.31578947  3747.36842105
#   4268.42105263  4789.47368421  5310.52631579  5831.57894737
#   6352.63157895  6873.68421053  7394.73684211  7915.78947368
#   8436.84210526  8957.89473684  9478.94736842 10000.        ]

In [84]:
print(li1.shape) # (9,)
print(li2.shape) # (10,)
print(li3.shape) # (20,)

(9,)
(10,)
(20,)


In [10]:
# 값이 다를 수 있습니다.
r1 = np.random.rand(2, 5)
r2 = np.random.rand(5, 5)
r3 = np.random.rand(8)

print(r1)
# [[0.57614483 0.73063258 0.27246055 0.21661481 0.08877755]
#  [0.41265303 0.67935852 0.38921903 0.66649004 0.47586199]]
print(r2)
# [[0.07353442 0.3770628  0.06070803 0.10123741 0.63826632]
#  [0.98591366 0.99821502 0.4428011  0.01528441 0.7924465 ]
#  [0.42231836 0.79382126 0.62384548 0.7091891  0.43492582]
#  [0.653554   0.80376989 0.11360542 0.39434994 0.34881749]
#  [0.72407747 0.66944767 0.39421464 0.25446252 0.91609148]]
print(r3)
# [0.08064439 0.38030084 0.7269083  0.81481334 0.3170198  0.35690691  0.36763132 0.88280171]

[[0.76780499 0.5034189  0.22054008 0.22579492 0.10348747]
 [0.10452716 0.7722156  0.55785404 0.9441642  0.88994367]]
[[0.8298528  0.2197327  0.67647234 0.75035607 0.33147988]
 [0.59426982 0.03710878 0.44383492 0.99378208 0.94302622]
 [0.00248727 0.81223781 0.77232554 0.40819946 0.12575967]
 [0.31897483 0.68843688 0.44423149 0.69565567 0.38506649]
 [0.35955457 0.03522995 0.46552198 0.76180739 0.52422641]]
[0.68021948 0.12232238 0.04293131 0.34542005 0.24464087 0.56450554
 0.52606009 0.79392814]


In [18]:
np.random.seed(42)

r4 = np.random.rand(2, 5)
r5 = np.random.rand(5, 5)
r6 = np.random.rand(8)

print(r4)
# [[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
#  [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]]
print(r5)
# [[0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
#  [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
#  [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]
#  [0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]
#  [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203]]
print(r6)
# [0.80839735 0.30461377 0.09767211 0.68423303 0.44015249 0.12203823 0.49517691 0.03438852]

[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]]
[[0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]
 [0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203]]
[0.80839735 0.30461377 0.09767211 0.68423303 0.44015249 0.12203823
 0.49517691 0.03438852]


In [23]:
# 값이 다를 수 있습니다.
ri1 = np.random.randint(0, 10, 5)
ri2 = np.random.randint(10, 20, 5)
ri3 = np.random.randint(0, 10, 8)

print(ri1)
# [0 3 1 7 3]
print(ri2)
# [11 15 15 19 13]
print(ri3)
# [5 1 9 1 9 3 7 6]

[4 2 7 5 2]
[10 12 14 12 10]
[4 9 6 6 8 9 9 2]


In [30]:
np.random.seed(42)

ri4 = np.random.randint(0, 10, 5)
ri5 = np.random.randint(10, 20, 5)
ri6 = np.random.randint(0, 10, 8)

print(ri4)
# [6 3 7 4 6]
print(ri5)
# [19 12 16 17 14]
print(ri6)
# [3 7 7 2 5 4 1 7]

[6 3 7 4 6]
[19 12 16 17 14]
[3 7 7 2 5 4 1 7]
