In [1]:
import numpy as np

In [4]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# array([[ 1,  2,  3,  4],
#        [ 5,  6,  7,  8],
#        [ 9, 10, 11, 12]])

np.delete(arr, 1, 0)
# array([[ 1,  2,  3,  4],
#        [ 9, 10, 11, 12]])

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [6]:
np.delete(arr, 1, 1)
# array([[ 1,  3,  4],
#        [ 5,  7,  8],
#        [ 9, 11, 12]])

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

In [9]:
np.delete(arr, 1)
# array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
np.delete(arr, [1,2], axis=0)
# array([[1, 2, 3, 4]])

array([[1, 2, 3, 4]])

In [15]:
np.delete(arr, [1,3], axis=1)
# array([[ 1,  3],
#        [ 5,  7],
#        [ 9, 11]])

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [16]:
np.delete(arr, [1,3], axis=None)
# array([ 1,  3,  5,  6,  7,  8,  9, 10, 11, 12])

array([ 1,  3,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
a = np.array([[1, 1], [2, 2], [3, 3]])
# array([[1, 1],
#        [2, 2],
#        [3, 3]])

np.insert(a, 1, 5)
# array([1, 5, 1, 2, 2, 3, 3])

np.insert(a, 1, 5, axis=0)
# array([[1, 1],
#        [5, 5],
#        [2, 2],
#        [3, 3]])

np.insert(a, 1, 5, axis=1)
# array([[1, 5, 1],
#        [2, 5, 2],
#        [3, 5, 3]])

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

In [29]:
np.insert(a, 1, [1, 2, 3], axis=1)
# array([[1, 1, 1],
#        [2, 2, 2],
#        [3, 3, 3]])

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [31]:
np.insert(a, 1, [1, 2, 3], axis=0)

ValueError: could not broadcast input array from shape (1,3) into shape (1,2)

In [32]:
np.insert(a, 1, [1, 2], axis=0)
# array([[1, 1],
#        [1, 2],
#        [2, 2],
#        [3, 3]])

array([[1, 1],
       [1, 2],
       [2, 2],
       [3, 3]])

In [37]:
np.insert(a, [0, 3], [10, 20], axis=0)
# array([[10, 20],
#        [ 1,  1],
#        [ 2,  2],
#        [ 3,  3],
#        [10, 20]])

array([[10, 20],
       [ 1,  1],
       [ 2,  2],
       [ 3,  3],
       [10, 20]])

In [43]:
np.insert(a, [0, 1, 2], [10, 20, 30], axis=1)
# array([[10,  1, 20,  1, 30],
#        [10,  2, 20,  2, 30],
#        [10,  3, 20,  3, 30]])

array([[10,  1, 20,  1, 30],
       [10,  2, 20,  2, 30],
       [10,  3, 20,  3, 30]])

In [44]:
np.insert(a, [0, 1, 2], [[10], [20], [30]], axis=1)
# array([[10,  1, 10,  1, 10],
#        [20,  2, 20,  2, 20],
#        [30,  3, 30,  3, 30]])

array([[10,  1, 10,  1, 10],
       [20,  2, 20,  2, 20],
       [30,  3, 30,  3, 30]])

In [45]:
np.insert(a, [1], [[10],[20],[30]], axis=1)

array([[ 1, 10,  1],
       [ 2, 20,  2],
       [ 3, 30,  3]])

In [48]:
np.insert(a, 1, [10,20,30], axis=1)

array([[ 1, 10,  1],
       [ 2, 20,  2],
       [ 3, 30,  3]])

In [61]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# array([[1, 2, 3],
#        [4, 5, 6],
#        [7, 8, 9]])

np.append(a, [10, 20, 30])
# array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 20, 30])

np.append(a, [[10, 20, 30]], axis=0)
# array([[ 1,  2,  3],
#        [ 4,  5,  6],
#        [ 7,  8,  9],
#        [10, 20, 30]])

np.append(a, [[10], [20], [30]], axis=1)
# array([[ 1,  2,  3, 10],
#        [ 4,  5,  6, 20],
#        [ 7,  8,  9, 30]])

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30]])

In [66]:
np.append(a, [10, 20, 30], axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [70]:
a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0, 0, 0))

np.trim_zeros(a, trim='f')
# array([1, 2, 3, 0, 2, 1, 0, 0, 0])

np.trim_zeros(a, trim='b')
# array([0, 0, 0, 1, 2, 3, 0, 2, 1])

np.trim_zeros(a, trim='fb')
# array([1, 2, 3, 0, 2, 1])

array([1, 2, 3, 0, 2, 1])

In [79]:
a = np.array([1, 2, 2, 3, 3, 3])
# array([1, 2, 2, 3, 3, 3])

np.unique(a)
# array([1, 2, 3])

np.unique(a, return_index=True)
# (array([1, 2, 3]), array([0, 1, 3]))

np.unique(a, return_index=True, return_inverse=True)
# (array([1, 2, 3]), array([0, 1, 3]), array([0, 1, 1, 2, 2, 2]))

np.unique(a, return_index=True, return_inverse=True, return_counts=True)
# (array([1, 2, 3]),
#  array([0, 1, 3]),
#  array([0, 1, 1, 2, 2, 2]),
#  array([1, 2, 3]))

(array([1, 2, 3]),
 array([0, 1, 3]),
 array([0, 1, 1, 2, 2, 2]),
 array([1, 2, 3]))

In [82]:
a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
# array([[1, 0, 0],
#        [1, 0, 0],
#        [2, 3, 4]])

np.unique(a, axis=0)
# array([[1, 0, 0],
#        [2, 3, 4]])

np.unique(a, axis=1)
# array([[0, 0, 1],
#        [0, 0, 1],
#        [3, 4, 2]])

array([[0, 0, 1],
       [0, 0, 1],
       [3, 4, 2]])

In [81]:
a

array([[1, 0, 0],
       [1, 0, 0],
       [2, 3, 4]])