In [1]:
import numpy as np

In [8]:
a = np.array([[1, 2], [3, 4]]) # a.shape=(2, 2)
b = np.array([[5, 6]]) # b.shape=(1, 2)

np.concatenate((a, b), axis=0)
# array([[1, 2],
#        [3, 4],
#        [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
a = np.array([[1, 2], [3, 4]]) # a.shape=(2, 2)
b = np.array([[5, 6]]) # b.shape=(1, 2)

np.concatenate((a, b), axis=1)
# array([[1, 2],
#        [3, 4],
#        [5, 6]])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [10]:
a = np.array([[1, 2], [3, 4]]) # a.shape=(2, 2)
b = np.array([[5, 6]]) # b.shape=(1, 2)

np.concatenate((a, b.T), axis=1)
# array([[1, 2, 5],
#        [3, 4, 6]])

array([[1, 2, 5],
       [3, 4, 6]])

In [11]:
a = np.array([[1, 2], [3, 4]]) # a.shape=(2, 2)
b = np.array([[5], [6]]) # b.shape=(2, 1)

np.concatenate((a, b), axis=1)
# array([[1, 2, 5],
#        [3, 4, 6]])

array([[1, 2, 5],
       [3, 4, 6]])

In [12]:
a = np.array([[1, 2], [3, 4]]) # a.shape=(2, 2)
b = np.array([[5], [6]]) # b.shape=(2, 1)

np.concatenate((a, b), axis=0)
# array([[1, 2, 5],
#        [3, 4, 6]])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1

In [13]:
a = np.array([[1, 2], [3, 4]]) # a.shape=(2, 2)
b = np.array([[5], [6]]) # b.shape=(2, 1)

np.concatenate((a, b.T), axis=0)
# array([[1, 2],
#        [3, 4],
#        [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
a = np.arange(1, 28).reshape(3, 3, 3)
b = np.arange(29, 38).reshape(3, 3, 1)

np.concatenate((a, b), axis=2)
# array([[[ 1,  2,  3, 29],
#         [ 4,  5,  6, 30],
#         [ 7,  8,  9, 31]],

#        [[10, 11, 12, 32],
#         [13, 14, 15, 33],
#         [16, 17, 18, 34]],

#        [[19, 20, 21, 35],
#         [22, 23, 24, 36],
#         [25, 26, 27, 37]]])

array([[[ 1,  2,  3, 29],
        [ 4,  5,  6, 30],
        [ 7,  8,  9, 31]],

       [[10, 11, 12, 32],
        [13, 14, 15, 33],
        [16, 17, 18, 34]],

       [[19, 20, 21, 35],
        [22, 23, 24, 36],
        [25, 26, 27, 37]]])

In [29]:
a = np.arange(1, 7).reshape(3, 2)
b = np.arange(7, 10).reshape(1, 3)
c = np.arange(10, 19).reshape(3, 3)

In [30]:
np.concatenate((a.T, b, c), axis=0)
# array([[ 1,  3,  5],
#        [ 2,  4,  6],
#        [ 7,  8,  9],
#        [10, 11, 12],
#        [13, 14, 15],
#        [16, 17, 18]])

array([[ 1,  3,  5],
       [ 2,  4,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [31]:
np.concatenate((a, b.T, c), axis=1)
# array([[ 1,  2,  7, 10, 11, 12],
#        [ 3,  4,  8, 13, 14, 15],
#        [ 5,  6,  9, 16, 17, 18]])

array([[ 1,  2,  7, 10, 11, 12],
       [ 3,  4,  8, 13, 14, 15],
       [ 5,  6,  9, 16, 17, 18]])