In [20]:
import numpy as np

In [21]:
x = np.arange(9.0)

np.split(x, 3)
# [array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [22]:
np.split(x, 4)
# ---------------------------------------------------------------------------
# TypeError                                 Traceback (most recent call last)
# ~/anaconda3/lib/python3.7/site-packages/numpy/lib/shape_base.py in split(ary, indices_or_sections, axis)
#     864     try:
# --> 865         len(indices_or_sections)
#     866     except TypeError:

# TypeError: object of type 'int' has no len()

# During handling of the above exception, another exception occurred:

# ValueError                                Traceback (most recent call last)
# <ipython-input-5-ff48ec4c4c29> in <module>
# ----> 1 np.split(x, 4)
#       2 # [array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

# <__array_function__ internals> in split(*args, **kwargs)

# ~/anaconda3/lib/python3.7/site-packages/numpy/lib/shape_base.py in split(ary, indices_or_sections, axis)
#     869         if N % sections:
#     870             raise ValueError(
# --> 871                 'array split does not result in an equal division')
#     872     return array_split(ary, indices_or_sections, axis)
#     873 

# ValueError: array split does not result in an equal division

ValueError: array split does not result in an equal division

In [27]:
np.split(x, (2, 3))
# [array([0., 1.]), array([2.]), array([3., 4., 5., 6., 7., 8.])]

[array([0., 1.]), array([2.]), array([3., 4., 5., 6., 7.])]

In [24]:
x = np.arange(8.0)

np.split(x, [3, 5, 6, 10])
# [array([0., 1., 2.]),
#  array([3., 4.]),
#  array([5.]),
#  array([6., 7.]),
#  array([], dtype=float64)]

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

In [28]:
x = np.arange(9.0).reshape(3, 3)

np.split(x, 3)
# [array([[0., 1., 2.]]), array([[3., 4., 5.]]), array([[6., 7., 8.]])]

np.split(x, 3, axis=1)
# [array([[0.],
#         [3.],
#         [6.]]),
#  array([[1.],
#         [4.],
#         [7.]]),
#  array([[2.],
#         [5.],
#         [8.]])]

[array([[0.],
        [3.],
        [6.]]),
 array([[1.],
        [4.],
        [7.]]),
 array([[2.],
        [5.],
        [8.]])]

In [29]:
np.split(x, 4, axis=1)

ValueError: array split does not result in an equal division

In [31]:
np.split(x, (1, 4))
# [array([[0., 1., 2.]]),
#  array([[3., 4., 5.],
#         [6., 7., 8.]]),
#  array([], shape=(0, 3), dtype=float64)]

[array([[0., 1., 2.]]),
 array([[3., 4., 5.],
        [6., 7., 8.]]),
 array([], shape=(0, 3), dtype=float64)]

In [30]:
np.split(x, (1, 4), axis=1)
# [array([[0.],
#         [3.],
#         [6.]]),
#  array([[1., 2.],
#         [4., 5.],
#         [7., 8.]]),
#  array([], shape=(3, 0), dtype=float64)]

[array([[0.],
        [3.],
        [6.]]),
 array([[1., 2.],
        [4., 5.],
        [7., 8.]]),
 array([], shape=(3, 0), dtype=float64)]

In [32]:
x = np.arange(8.0)

np.split(x, [5, 3, 6, 10])
# [array([0., 1., 2., 3., 4.]),
#  array([], dtype=float64),
#  array([3., 4., 5.]),
#  array([6., 7.]),
#  array([], dtype=float64)]

[array([0., 1., 2., 3., 4.]),
 array([], dtype=float64),
 array([3., 4., 5.]),
 array([6., 7.]),
 array([], dtype=float64)]

In [33]:
x = np.arange(9.0).reshape(3, 3)

np.hsplit(x, 3)
# [array([[0.],
#         [3.],
#         [6.]]),
#  array([[1.],
#         [4.],
#         [7.]]),
#  array([[2.],
#         [5.],
#         [8.]])]

np.split(x, 3, axis=1)
# [array([[0.],
#         [3.],
#         [6.]]),
#  array([[1.],
#         [4.],
#         [7.]]),
#  array([[2.],
#         [5.],
#         [8.]])]

[array([[0.],
        [3.],
        [6.]]),
 array([[1.],
        [4.],
        [7.]]),
 array([[2.],
        [5.],
        [8.]])]

In [35]:
x = np.arange(9.0).reshape(3, 3)

np.vsplit(x, 3)
# [array([[0., 1., 2.]]), array([[3., 4., 5.]]), array([[6., 7., 8.]])]

np.split(x, 3, axis=0)
# [array([[0., 1., 2.]]), array([[3., 4., 5.]]), array([[6., 7., 8.]])]

[array([[0., 1., 2.]]), array([[3., 4., 5.]]), array([[6., 7., 8.]])]

In [38]:
x = np.arange(16.0).reshape(2, 2, 4)

np.dsplit(x, 2)
# [array([[[ 0.,  1.],
#          [ 4.,  5.]],
 
#         [[ 8.,  9.],
#          [12., 13.]]]),
#  array([[[ 2.,  3.],
#          [ 6.,  7.]],
 
#         [[10., 11.],
#          [14., 15.]]])]

np.split(x, 2, axis=2)
# [array([[[ 0.,  1.],
#          [ 4.,  5.]],
 
#         [[ 8.,  9.],
#          [12., 13.]]]),
#  array([[[ 2.,  3.],
#          [ 6.,  7.]],
 
#         [[10., 11.],
#          [14., 15.]]])]

[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]),
 array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]