In [50]:
import numpy as np

In [51]:
# 파이썬 리스트 indexing
l = [1, 2, 3, 4, 5]

In [52]:
print("l[0] : ", l[0]) # 1
print("l[1] : ", l[1]) # 2
print("l[2] : ", l[2]) # 3
print("l[3] : ", l[3]) # 4
print("l[4] : ", l[4]) # 5

l[0] :  1
l[1] :  2
l[2] :  3
l[3] :  4
l[4] :  5


In [53]:
print("l[5] : ", l[5])

IndexError: list index out of range

In [54]:
print("l[-1] : ", l[-1]) # 5
print("l[-2] : ", l[-2]) # 4
print("l[-3] : ", l[-3]) # 3
print("l[-4] : ", l[-4]) # 2
print("l[-5] : ", l[-5]) # 1

l[-1] :  5
l[-2] :  4
l[-3] :  3
l[-4] :  2
l[-5] :  1


In [55]:
print("l[-0] : ", l[-0]) # 1
print("l[0] : ", l[0]) # 1

l[-0] :  1
l[0] :  1


In [56]:
# 파이썬 튜플 indexing
t = (1, 2, 3, 4, 5)

In [57]:
print("t[0] : ", t[0]) # 1
print("t[1] : ", t[1]) # 2
print("t[2] : ", t[2]) # 3
print("t[3] : ", t[3]) # 4
print("t[4] : ", t[4]) # 5

t[0] :  1
t[1] :  2
t[2] :  3
t[3] :  4
t[4] :  5


In [58]:
print("t[5] : ", t[5])

IndexError: tuple index out of range

In [59]:
print("t[-1] : ", t[-1]) # 5
print("t[-2] : ", t[-2]) # 4
print("t[-3] : ", t[-3]) # 3
print("t[-4] : ", t[-4]) # 2
print("t[-5] : ", t[-5]) # 1

t[-1] :  5
t[-2] :  4
t[-3] :  3
t[-4] :  2
t[-5] :  1


In [60]:
print("t[-0] : ", t[-0]) # 1
print("t[0] : ", t[0]) # 1

t[-0] :  1
t[0] :  1


In [61]:
l[1:3] # [2, 3]

[2, 3]

In [62]:
l[1:4] # [2, 3, 4]

[2, 3, 4]

In [63]:
print("2번 인덱스부터 마지막 인덱스까지 = ", l[2:]) # [3, 4, 5]
print("첫번째 인덱스부터 2번 인덱스까지 = ", l[:3]) # [1, 2, 3]
print("모든 인덱스 = ", l[:]) # [1, 2, 3, 4, 5]

2번 인덱스부터 마지막 인덱스까지 =  [3, 4, 5]
첫번째 인덱스부터 2번 인덱스까지 =  [1, 2, 3]
모든 인덱스 =  [1, 2, 3, 4, 5]


In [64]:
print(l[1::2]) # [2, 4]
print(l[:4:2]) # [1, 3]
print(l[::2]) # [1, 3, 5]

[2, 4]
[1, 3]
[1, 3, 5]


In [65]:
l[::-1] # [5, 4, 3, 2, 1]

[5, 4, 3, 2, 1]

In [66]:
a = np.array([1, 2 , 3, 4, 5])

print("a[0] : ", a[0]) # 1
print("a[1] : ", a[1]) # 2
print("a[2] : ", a[2]) # 3
print("a[3] : ", a[3]) # 4
print("a[4] : ", a[4]) # 5

print("a[-0] : ", a[-0]) # 1
print("a[-1] : ", a[-1]) # 5
print("a[-2] : ", a[-2]) # 4
print("a[-3] : ", a[-3]) # 3
print("a[-4] : ", a[-4]) # 2

a[0] :  1
a[1] :  2
a[2] :  3
a[3] :  4
a[4] :  5
a[-0] :  1
a[-1] :  5
a[-2] :  4
a[-3] :  3
a[-4] :  2


In [67]:
print("a[6] = ", a[6])

IndexError: index 6 is out of bounds for axis 0 with size 5

In [68]:
l[2:4:2]

[3]

In [69]:
b = np.arange(1, 10)
print(b[2:7:2]) # [3 5 7]

[3 5 7]


In [70]:
c = np.arange(1, 16).reshape(3, 5)
print(c)
# [[ 1  2  3  4  5]
#  [ 6  7  8  9 10]
#  [11 12 13 14 15]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [71]:
print("c[0, 0] = ", c[0, 0]) # 1
print("c[0, 1] = ", c[0, 1]) # 2
print("c[0, 2] = ", c[0, 2]) # 3
print("c[0, 3] = ", c[0, 3]) # 4
print("c[0, 4] = ", c[0, 4]) # 5
print("c[1, 0] = ", c[1, 0]) # 6
print("c[1, 1] = ", c[1, 1]) # 7
print("c[1, 2] = ", c[1, 2]) # 8
print("c[1, 3] = ", c[1, 3]) # 9
print("c[1, 4] = ", c[1, 4]) # 10
print("c[2, 0] = ", c[2, 0]) # 11
print("c[2, 1] = ", c[2, 1]) # 12
print("c[2, 2] = ", c[2, 2]) # 13
print("c[2, 3] = ", c[2, 3]) # 14
print("c[2, 4] = ", c[2, 4]) # 15

c[0, 0] =  1
c[0, 1] =  2
c[0, 2] =  3
c[0, 3] =  4
c[0, 4] =  5
c[1, 0] =  6
c[1, 1] =  7
c[1, 2] =  8
c[1, 3] =  9
c[1, 4] =  10
c[2, 0] =  11
c[2, 1] =  12
c[2, 2] =  13
c[2, 3] =  14
c[2, 4] =  15


In [72]:
for i in range(c.shape[0]) :
    for j in range(c.shape[1]) :
        print("c[%d, %d] = %d" % (i, j, c[i, j]), end=' ')
    print()
    
# c[0, 0] = 1 c[0, 1] = 2 c[0, 2] = 3 c[0, 3] = 4 c[0, 4] = 5 
# c[1, 0] = 6 c[1, 1] = 7 c[1, 2] = 8 c[1, 3] = 9 c[1, 4] = 10 
# c[2, 0] = 11 c[2, 1] = 12 c[2, 2] = 13 c[2, 3] = 14 c[2, 4] = 15 

c[0, 0] = 1 c[0, 1] = 2 c[0, 2] = 3 c[0, 3] = 4 c[0, 4] = 5 
c[1, 0] = 6 c[1, 1] = 7 c[1, 2] = 8 c[1, 3] = 9 c[1, 4] = 10 
c[2, 0] = 11 c[2, 1] = 12 c[2, 2] = 13 c[2, 3] = 14 c[2, 4] = 15 


In [75]:
d = np.arange(1, 28).reshape((3, 3, 3))
print(d.shape) # (3, 3, 3)
print(d)
# [[[ 1  2  3]
#   [ 4  5  6]
#   [ 7  8  9]]

#  [[10 11 12]
#   [13 14 15]
#   [16 17 18]]

#  [[19 20 21]
#   [22 23 24]
#   [25 26 27]]]

(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [78]:
print("d[0, 0, 0] = ", d[0, 0, 0]) # 1
print("d[1, 1, 0] = ", d[1, 1, 0]) # 13
print("d[2, 2, 0] = ", d[2, 2, 0]) # 25
print("d[0, 2, 2] = ", d[0, 2, 2]) # 9
print("d[1, 0, 1] = ", d[1, 0, 1]) # 11

d[0, 0, 0] =  1
d[1, 1, 0] =  13
d[2, 2, 0] =  25
d[0, 2, 2] =  9
d[1, 0, 1] =  11


In [81]:
e = np.arange(1, 11)
idx = np.array([0, 2, 6, 8])
print(e) # [ 1  2  3  4  5  6  7  8  9 10]
print(e[idx]) # [1 3 7 9]

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 7 9]
